---
title: "Fire Stories"
description: |
  A collection of stories I've written about experiences working on wildfires.
author:
  - name: Rebecca Weber 
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Story Time - The Labour Day Fires
 
The morning of September 8,2020th began as many do on when fighting wildfires:- slow, but crackling with an edge of anticipation. Medford Crew 10 was assigned to the Grizzly Creek Fire near Howard Prairie -, just east of Ashland,OR - a confusing fire that had burned in fits and starts through the most extensive plots of Pacific yew I’d ever seen. Our work consisted of extinguishing smoldering stumps and logs, and then thinning out and limbing up the remaining vegetation in order to prevent a reburn. The whole thing was like a backwards fuels treatment, and no one was excited about it. The silver lining redeeming an otherwise monotonous day: our crew was “IA available.” This meant we could leave at any moment to respond to a new fire start, and an extreme fire weather forecast featuring high winds and hot temps all but assured that we’d have a new assignment by noon.
 
Tantalized by the promise of hotline, I think we all felt the eager side of anxious when we saw the treetops tossing in gusts clocking at least 30 mph gusts. Our squad paused between digging out great stump holes to watch small branches drifting down fall down from the canopies of 100 foot tall Douglas-firs, and chatted idly about commenting on how winds like these make us feel so small and powerless. Little did we know the predictive power of that idle chatter.
 
By 10 am we received the call. “There’s a grass fire near Ashland, we need you here quick.” As we wound down Dead Indian Memorial Road (insert hyperlink: https://mailtribune.com/news/since-you-asked/how-dead-indian-memorial-road-got-its-name) to the Rogue Valley, a gunmetal-grey plume emerged over the Siskiyou Crest and we wondered, "is that where we’re going? Doesn’t look like smoke from just a grass fire..."

Later we would find out that the plume had been created by the beginnings of the Slater Fire, and that the dark smoke was being produced as the misnamed town of Happy Camp went up in flames. But then the road curved north, the Slater plume faded into our peripherals, and an incident of more immediate concern demanded our attention with smoke boiling up along the I-5 corridor. This was the Almeda Dr Fire. 
 
The next hour was a mess of traffic confusion. We flicked on lights and sirens to maneuver through the gridlock that was already building outside of Ashland, finally sidling our way onto the I-5, only to drive laps north and south trying to determine the best access point to the fire. As jammed as the off-ramps and side streets were with cars, the interstate was echoingly empty, save for a few abandoned cars, jackknifed semis and the occasional caravan of sheriffs and other police vehicles that would go screaming by. It was a good thing, too, that no one else was on the interstate, because as we tore north towards Talent, thick, blinding smoke obscured limited our visibility to mere feet ahead of us and  the sides of the truck heated up from flames licking up the median and stretching over the soft shoulder, pushed nearly horizontal by devilishly strong winds. When we saw the first black skeleton of a house, already completely consumed by fire that had come and gone before anyone could do anything, it finally clicked. This was no normal grass fire. The winds we had watched tossing the big Douglas-firs could push the fire towards the towns of Phoenix and Medford faster than we could respond. 
 
Unable to see the fire and where it was spreading through the smoke, we staged by an underpass and awaited instructions. That’s when the texts started to streaming in from family and friends who livinge in the area. Where are you? Are you working this fire? What should we do? Should we evacuate? Where should we go? Each of us tried to be there for our people while the radio chattered constant updates and directions: "the fire has crossed I5;, the fire is held up at some orchards;, we’re bringing in air support from Idaho, they’ll be here in an hour." Mercifully, our superintendent called and told us to quit scanning tactical and command channels on the radio and, to only listen to the crew channel. He explained that he wanted us to break into one-squad mods to cover as much ground as possible and it would be confusing enough to coordinate without trying to filter out radio traffic from the greater area that didn’t pertain to our mission. I suspect he also wanted to keep us calm. 
 
On most fires, the strategy involves establishing an anchor point and placing a control line around the flank of a fire to curtail its spread, rather like using a towel to mopping up a spilled glass of water. On this fire, that option didn’t exist. How could we construct a fire line through neighborhoods, weed farms, barbed wire fences overgrown with blackberry bushes, hayfields, junkyards that could hold 10-15 ft flame lengths in winds so strong they would blow off our hardhats? All of this  with only 4-8 person mods working per location? We tried again and again, only to watch the hillside ahead of us spot with flame and within minutes be completely consumed, or for the fire to wrap around the other side of a house before we could get there, or for someone to stumble upon a propane tank and send us high-tailing away from a potential  explosion. 

We did what we could, scratching line around homes, gathering garden hoses and buckets to wet down everything flammable in sight and tamp down encouraching flames, soaking wood piles, activating sprinklers, limbing trees hanging over fences and stripping away vegetation cuddling up to the sides of buildings. Sometimes we were successful, and would hand off the situation to firefighters from Jackson County Fire Districts who had more training and expertise in structural fire than we did. But for the most part, the winds kept pushing the fire further, faster, than we could arrive, and any attempts at control were soon compromised by wind-blown embers creating new hazards wherever they landed. All we could do was to save what we could, keep chasing the head of the fire, and hope that the winds would die down. 
 
And then there was the smell. Have I mentioned how this fire smelled? It smelt bad. Unlike the forest or sagebrush or grasslands, which burn with a variety of comforting aromas, the smell from the Almeda Dr Fire was acrid and toxic- the smell of metal, plastic, paint, rubber, appliances, trash, photo albums, all burning. That smell is not comforting. 
 
As hectic as the whole situation was, there were strange islands of calm when all we could do was observe. In the late afternoon we all gathered on a hillside while low-flying tankers dropped load after $20k load of fire retardant on the east side of I-5. For once I felt nothing but gratitude for the expensive, trumped-up chicken shit those planes dropped; without those wide bands of retardant and a fortunate decrease in wind speeds, I’m not sure what would have stopped that fire. Shortly after the drops, our efforts finally began to gain traction, successfully punching in line around some beautiful homes on a hillside. In celebration and solidarity, everyone there lit cigarettes and huddled in a circle, anything to soothe our strung-out nerves. Non-smokers, ex-smokers, and current smokers alike inhaled the familiar stinging smoke and exhaled a sigh of released tension. The work was not done, but moments like these were respites in the storm that fueled us through the next challenge. 
 
Late at the end of the night, our squad patrolled some line we had punched in through an oak woodland on a property where the owners had mercifully kept up with fuel treatments, helping to keep fire activity to a minimum. The property sat up on a hill, so as we aligned burning logs with the slope -, careful not to stir up embers -, and buried coals in dirt to keep the wind from undoing our hard work, we could look over the Rogue Valley where fire still raged. The subsiding ferocity of the fire that came with night was punctuated by the periodic *BOOMS* and fireballs of exploding paint cans or propane tanks. In the relative peace of those moments, I wish I could say that I experienced some philosophical revelations about the events that had unfolded, and why - but honestly we were all too exhausted to think beyond the task at hand.
 
The questions came later. Not the next day, when we actually did respond to the Slater Fire whose ominous plume we had observed with trepidation, nor the next, when, instead of working with flames licking at our heels,  we had the chance to plan and perform structure protection outside of Takilma in advance of the flames. But after the fire season, when my body was sitting at home fiending for the adrenaline that had fueled it in the previous weeks while my brain struggled to  wrangle attention towards schoolwork and research – this is when the questions emerged. As I returned to my regular running routine, the questions unspooled beneath my pounding feet, questions that I am still unable to answer: Did we do enough? Could we have done more? Could we have been better prepared?  On a larger scale, was any of this destruction preventable? If so, how? If so, why was nothing done? 
